name: cleanup packages

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.1.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: tunnelchik
          cut-off: 1d
          keep-n-most-recent: 10
